In [48]:
def func(x):
    return 2 * x

In [49]:
func(5)

10

In [50]:
# z = sin(y) = sin(x^2)
# z = cos(x ^ 2) * 2x
import numpy as np

def func_(x):
    return np.cos(x ** 2) * 2 * x

In [51]:
func_(2)

np.float64(-2.6145744834544478)

In [52]:
def func__(x):
    return np.exp(np.sin(x**2)) * func_(x)

func__(2)

np.float64(-1.226664708936842)

In [53]:
import torch

#define x
x = torch.tensor(3.0, requires_grad=True)

#define y
y  = x ** 2

#compute backward derivative
y.backward()

# get the value for the gradient 
x.grad


tensor(6.)

In [54]:
import torch 

a = torch.tensor(4.0, requires_grad=True)
b = a**2
c = torch.sin(b)

c.backward()
a.grad


tensor(-7.6613)

In [55]:
def loss(target, prediction):
    epsilon = 1e-8
    prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
    return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))

In [ ]:
x = torch.tensor(6.7)
y = torch.tensor(0)

w = 1
b = 0

for i in range(1000):
    z = w*x + b
    y_pred = torch.sigmoid(z)

    slope_w = (y_pred - y) * x
    slope_b = (y_pred - y)

    learning_rate = 0.01

    w = w - learning_rate * slope_w
    b = b - learning_rate * slope_b

print(w)
print(b)

tensor(-0.8694)
tensor(-0.2790)


In [67]:
x = torch.tensor(6.7, requires_grad=True)
y = torch.tensor(0.0, requires_grad=True)

w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

z = w * x + b
y_pred = torch.sigmoid(z)

l = loss(y, y_pred)
l.backward()
print(w.grad, b.grad)

tensor(6.6918) tensor(0.9988)


In [93]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

In [94]:
y = (x**2).mean()
y.backward()
print(x.grad)
x.grad.zero_()
# x.requires_grad_(False)
print(x)

tensor([0.6667, 1.3333, 2.0000])
tensor([1., 2., 3.], requires_grad=True)


we have to clear the gradients before giving backwards again 
the gradients have to be cleared before giving for the forward and backward passes again

to disable the tracking of the derivatives during post training phase, we have to disable the autograd tracking
this can be done using 

requires_grad(false) - method - 1 = this will remove the x from the autograd tracking
detach() - method 2 = this will create a copy of a tracking variable x in the non tracking form 
with torch.no_grad() - this will create functions of a tracking variables which will be non tracking

In [96]:
z = x.detach()
z

tensor([1., 2., 3.])