In [548]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [549]:
df = pd.read_csv("../datasets/placement.csv")
df

,cgpa,resume_score,placed
0,8.14,6.52,1
1,6.17,5.17,0
2,8.27,8.86,1
3,6.88,7.27,1
4,7.52,7.30,1
...,...,...,...
95,6.33,6.38,0
96,8.23,7.76,1
97,6.65,7.78,0
98,8.14,5.63,1


In [550]:
from sklearn.model_selection import train_test_split
x = df[["cgpa", "resume_score"]]
y = df[["placed"]]
x_train, x_test, y_train, y_test =train_test_split(x, y, test_size=0.2, random_state=42)

In [551]:
from sklearn.linear_model import Perceptron

model = Perceptron()
model.fit(x_train, y_train)
model.coef_

c:\Users\Nadakishore\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[ 44.42, -41.1 ]])

In [552]:
pred = model.predict(x_test)

from sklearn.metrics import accuracy_score

accuracy_score(y_test, pred)

0.75

In [553]:
def func(x):
    return 1 / (1 + np.exp(-x)) > 0.5

In [554]:
class Perceptron:
    def __init__(self, epoch = 1000, learning_rate = 0.01):
        self.epoch = epoch
        self.lr = learning_rate
        self.weights = None

    def fit(self, x, y):
        x_ = np.insert(x, 0, 1, axis = 1)
        self.weights = np.ones(x_.shape[1])
        y_ = np.asarray(y)
        for i in range(self.epoch):
            indices = np.random.permutation(x_.shape[0])
            for index in indices:
                xi = x_[index]
                yi = y_[index]
                y_pred = np.dot(xi, self.weights)
                y_pred = func(y_pred)
                self.weights = self.weights  + self.lr * xi * (yi - y_pred)

        return self.weights

    def predict(self, x):
        x_ = np.insert(x, 0, 1, axis = 1)
        y_pred = np.dot(x_, self.weights)
        y_pred=  func(y_pred)
        return y_pred


In [555]:
model = Perceptron()
model.fit(x_train, y_train)


array([-6.21  ,  0.8169, -0.0135])

In [556]:
pred = model.predict(x_test)
accuracy_score(y_test, pred)

0.75

In [557]:
x_ = np.insert(x_train, 0, 1, axis = 1)
weights = np.ones(x_.shape[1])
x_[0]

array([1.  , 6.94, 6.87])

In [561]:
y_train[y_train == 0] = -1

In [564]:
class GD_perceptron:
    def __init__(self, lr = 0.01, epoch = 1000):
        self.epoch = epoch
        self.lr = lr
        self.weights = None

    def fit(self, x, y):
        x_ = np.insert(x, 0, 1, axis = 1)
        self.weights = np.ones(x_.shape[1])
        y_ = np.asarray(y)
        
        for j in range(self.epoch):
            for i in range(x.shape[0]):
                z = self.weights[0] * x_[i][0] + self.weights[1] * x_[i][1] + self.weights[2] * x_[i][2]
                if (z * y_[i]) <= 0:
                    self.weights[1] += self.lr * y_[i] * x_[i][1]
                    self.weights[2] += self.lr * y_[i] * x_[i][2]
                    self.weights[0] += self.lr * y_[i] * x_[i][0]
        return self.weights

    def predict(self, x):
        x_ = np.insert(x, 0, 1, axis = 1)
        y_pred = np.dot(x_, self.weights)
        y_pred = func(y_pred)
        return y_pred

        

In [565]:
model = GD_perceptron()
model.fit(x_train, y_train)

C:\Users\Nadakishore\AppData\Local\Temp\ipykernel_9460\564675130.py:16: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  self.weights[1] += self.lr * y_[i] * x_[i][1]
C:\Users\Nadakishore\AppData\Local\Temp\ipykernel_9460\564675130.py:17: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  self.weights[2] += self.lr * y_[i] * x_[i][2]
C:\Users\Nadakishore\AppData\Local\Temp\ipykernel_9460\564675130.py:18: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  self.weights[0] += self

array([-6.22  ,  0.8954,  0.0341])

In [566]:
pred = model.predict(x_test)
accuracy_score(y_test, pred)

1.0