initialisation

In [126]:
import torch

print(torch.__version__)

2.11.0+cu128


In [127]:
if torch.cuda.is_available():
  print("GPU available... using GPU")
  print(torch.cuda.get_device_name()[0])
else:
  print("GPU not available... connnecting to CPU")

GPU available... using GPU
T


creating a tensor

In [128]:
#using empty to create a tensor
#this allocates memory in space and returns the value which is already present
# in this memory space

arr = torch.empty(2,3)
print(arr)
print(type(arr))

tensor([[638.5696,   0.0000,   0.0000],
        [  0.0000,   0.0000,   0.0000]])
<class 'torch.Tensor'>


In [129]:
#using zeros to create the tensor
#create a array of the given size filled with zeros

arr = torch.zeros(2,3)
print(arr)
print(type(arr))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>


In [130]:
#using ones to create a tensor
# creates an array filled with ones

arr = torch.ones(2,3)
print(arr)
print(type(arr))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
<class 'torch.Tensor'>


In [131]:
#using torch.rand to create a random tensor of the given shape
#this value will not be repeated thus, we need to set the seed for this

arr = torch.rand(2,3)
print(arr)
print(type(arr))

tensor([[0.1724, 0.8462, 0.1072],
        [0.7113, 0.1406, 0.2950]])
<class 'torch.Tensor'>


In [132]:
# setting the seed for the rand function

torch.manual_seed(100)
arr = torch.rand(2,3)
print(arr)
print(type(arr))

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
<class 'torch.Tensor'>


In [133]:
#to create a custom tensor, we use torch.tensor

arr = torch.Tensor([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))

tensor([[1., 2., 3.],
        [4., 5., 6.]])
<class 'torch.Tensor'>


In [134]:
#other methods include torch.arange - creates an array from range provided

arr = torch.arange(0, 10)
print(arr)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [135]:
#torch.eye is used to get the identity matrix of a particular shape

arr = torch.eye(5)
print(arr)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [136]:
#using linspace to create an array
#divides the range equally into n divisions and returns the values

arr = torch.linspace(0, 10, 10)
print(arr.shape)

torch.Size([10])


In [137]:
# to create a fill matrix with a fill value, we use torch.full

arr = torch.full((3,3), 5)
print(arr)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


type and shape of the tensor

In [138]:
#getting the shape of the tensor

arr = torch.Tensor([[1,2,3], [4,5,6]])
arr.shape

torch.Size([2, 3])

In [139]:
# creating an empty array of the same shape

arr1 = torch.empty(arr.shape)
arr1.shape

torch.Size([2, 3])

In [140]:
#another method to create a array of same shape and size

arr1 = torch.empty_like(arr)
print(arr1)
print(arr1.shape)

tensor([[1.5929e+03, 4.3694e-41, 6.0051e+03],
        [0.0000e+00, 9.1835e-41, 0.0000e+00]])
torch.Size([2, 3])


In [141]:
# creating a zero array of the same shape

arr1 = torch.zeros_like(arr)
print(arr1)
print(arr1.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])


In [142]:
#creating a random array of the same shape
#generates values between 0 and 1

arr1 = torch.rand_like(arr)
print(arr1, arr1.shape)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]]) torch.Size([2, 3])


In [143]:
# to find the data type of a tensor, we use dtype

arr.dtype

torch.float32

In [144]:
arr1 = torch.tensor([[1,2,3] , [4,5,6]], dtype = torch.float32)
print(arr1.dtype)
arr_ = arr1.to(torch.int32)
print(arr_.dtype)

# there are two different constructors torch.tensor and torch.Tensor - the Tensor does not have dtype whereas tensor has a dtype argument


torch.float32
torch.int32


mathematical operations

In [145]:
torch.manual_seed(100)
arr1 = torch.rand(2,2)
arr2 = torch.rand(2,2)
arr1, arr2

(tensor([[0.1117, 0.8158],
         [0.2626, 0.4839]]),
 tensor([[0.6765, 0.7539],
         [0.2627, 0.0428]]))

In [146]:
print(arr1 + arr2)

tensor([[0.7882, 1.5698],
        [0.5253, 0.5267]])


In [147]:
print(arr2 - arr1)

tensor([[ 5.6484e-01, -6.1932e-02],
        [ 1.2857e-04, -4.4104e-01]])


In [148]:
print(arr1 * arr2)

tensor([[0.0755, 0.6151],
        [0.0690, 0.0207]])


In [149]:
print(arr1 / arr2)

tensor([[ 0.1651,  1.0821],
        [ 0.9995, 11.2951]])


In [150]:
print(arr1 // arr2)

tensor([[ 0.,  1.],
        [ 0., 11.]])


In [151]:
print(arr1 + 2)

tensor([[2.1117, 2.8158],
        [2.2626, 2.4839]])


In [152]:
print(arr2 - 3)

tensor([[-2.3235, -2.2461],
        [-2.7373, -2.9572]])


In [153]:
print(arr1 * 8)

tensor([[0.8933, 6.5267],
        [2.1005, 3.8710]])


In [154]:
print(arr1 / 8)

tensor([[0.0140, 0.1020],
        [0.0328, 0.0605]])


In [155]:
print(arr1 // 4)

tensor([[0., 0.],
        [0., 0.]])


In [156]:
print(arr1 % 2)

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])


In [157]:
print(arr1 ** 2)

tensor([[0.0125, 0.6656],
        [0.0689, 0.2341]])


In [158]:
arr = torch.tensor([1,-2,3,-4])
torch.abs(arr)
torch.neg(arr)

tensor([-1,  2, -3,  4])

In [159]:
arr = torch.tensor([1.2, 2.4, 3.6, 4.5])
torch.round(arr)

# we also have ceil, floor etc.

tensor([1., 2., 4., 4.])

In [160]:
torch.clamp(arr, max=3, min = 2)

tensor([2.0000, 2.4000, 3.0000, 3.0000])

In [161]:
x = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.float32)
x

tensor([[8., 0., 4.],
        [3., 8., 8.]])

In [162]:
torch.sum(x)
torch.sum(x, dim = 0)
torch.sum(x, dim = 1)

tensor([12., 19.])

In [163]:
torch.mean(x)
torch.mean(x, dim = 0)
torch.mean(x, dim = 1)

#torch.mean works with float only

tensor([4.0000, 6.3333])

In [164]:
torch.median(x)
torch.median(x, dim = 0)
torch.median(x, dim = 1)

torch.return_types.median(
values=tensor([4., 8.]),
indices=tensor([2, 1]))

In [165]:
torch.std(x)

tensor(3.3714)

In [166]:
torch.var(x)

tensor(11.3667)

In [167]:
torch.argmax(x)

tensor(0)

In [168]:
torch.argmin(x)

tensor(1)

In [169]:
x = torch.randint(size = (2,3), low = 0, high = 10)
y = torch.randint(size = (3,2), low = 0, high = 10)

In [170]:
print(x)
print(y)

tensor([[4, 4, 1],
        [0, 4, 3]])
tensor([[8, 7],
        [4, 6],
        [0, 1]])


In [171]:
torch.matmul(x, y)

tensor([[48, 53],
        [16, 27]])

In [172]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])

torch.dot(x,y)

tensor(11)

In [173]:
x = torch.randint(size = (2,3), low = 0, high = 10)
print(x)
torch.transpose(x, 0, 1)

tensor([[9, 9, 8],
        [0, 7, 0]])


tensor([[9, 0],
        [9, 7],
        [8, 0]])

In [174]:
x =torch.eye(3,3)
torch.det(x)
torch.inverse(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [175]:
x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[1,4,7],[2,3,4]])
x > y

# we can have other relational operations such as >, < , >=, <= etc as well


tensor([[False, False, False],
        [ True,  True,  True]])

In [176]:
torch.log(x)

tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])

In [177]:
torch.exp(x)

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [178]:
torch.sqrt(x)

tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])

In [179]:
torch.sigmoid(x)

tensor([[0.7311, 0.8808, 0.9526],
        [0.9820, 0.9933, 0.9975]])

In [180]:
y = x.to(torch.float32)
torch.softmax(y, 0)

tensor([[0.0474, 0.0474, 0.0474],
        [0.9526, 0.9526, 0.9526]])

inplace functions

In [181]:
m = torch.randint(size = (2,3), low = 0, high = 10)
n = torch.randint(size = (2,3), low = 0, high = 10)
print(m)
print(n)
m.add_(n)
print(m)

tensor([[0, 9, 5],
        [7, 3, 9]])
tensor([[4, 0, 5],
        [7, 5, 9]])
tensor([[ 4,  9, 10],
        [14,  8, 18]])


In [182]:
m.relu_()

tensor([[ 4,  9, 10],
        [14,  8, 18]])

In [183]:
# the underscore after the function name indicates the function is an inplace function

In [184]:
# to copy a tensor, we use the clone function

a = torch.tensor([1,2,3])
b = a.clone()

a == b
id(a), id(b)

(133916753519840, 133916761778176)

using GPUs for computation

In [185]:
torch.cuda.is_available()

True

In [186]:
device = torch.device("cuda")

In [187]:
a = torch.tensor([1,2,3,4], device = device)
a

tensor([1, 2, 3, 4], device='cuda:0')

In [188]:
a = torch.tensor([1,2,3,4])
a.to(device)

tensor([1, 2, 3, 4], device='cuda:0')

In [189]:
a = torch.randint(size = (4,4), low = 0, high = 10)
print(a.shape)
a_ = a.reshape(2,8)
print(a_.shape)

torch.Size([4, 4])
torch.Size([2, 8])


In [190]:
a_ = a.flatten()
print(a_.shape)


torch.Size([16])


In [191]:
x = torch.rand(2,3,4)
x_ =  x.permute(2,0, 1)
print(x.shape)
print(x_.shape)

torch.Size([2, 3, 4])
torch.Size([4, 2, 3])


In [192]:
# we can use unsqueeze to add new dimensions inside tensors
# unsqueeze increases the dimensions whereas squeeze decreases the dimensions
# we use the numpy function to convert the value from tensor to numpy array
# we use the torch.from_numpy() to convert from numpy to torch.tensor